version: "3.7"
services:
  app:
    build: ./
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: users-api
      DB_HOST: db
    volumes:
      - ./:/app
    container_name: users-api
    restart: always
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
